# Site settings
title:        Kevin Falting </>
email:        kevinfalting@gmail.com
description:  Building community, writing software, and always learning.
url:          "http://kevinfalting.com"

# Social
twitter:    FaltingKevin
github:     kevinfalting
facebook:   kevin.falting.5
instagram:  kevinfalting
lastfm:     kevinfalting1
linkedin:   kevin-falting-33981313a
spotify:    kevinfalting

# Build settings
markdown: kramdown

# Collections
collections:
- portfolio
